language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
sudo: required
notifications:
  email:
    - damiancritchfield@outlook.com
  on_success: always
  on_failure: always
branches:
  only:
    - master
install:
  - echo Skipping install step
script:
  - mvn clean package -Dmaven.test.skip=true -Dgpg.skip=true
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "damiancritchfield"
  - git config --local user.email "damiancritchfield@outlook.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true